defaults: &defaults
  host: <%= GlobalSetting.redis_host %>
  port: <%= GlobalSetting.redis_port %>
  password: <%= GlobalSetting.redis_password %>
  db: <%= GlobalSetting.redis_db %>

development:
  <<: *defaults
  host: "albacore.redistogo.com"
  port: 10653
  password: "0f39592563353ee0c25ef6e84a9b7e70"
  
profile:
  <<: *defaults

test:
  <<: *defaults
  db: 1

staging:
  <<: *defaults

production:
  <<: *defaults
  host: "albacore.redistogo.com"
  port: 10653
  password: "0f39592563353ee0c25ef6e84a9b7e70"
