defaults: &defaults
  host: <%= GlobalSetting.redis_host %>
  port: <%= GlobalSetting.redis_port %>
  password: <%= GlobalSetting.redis_password %>
  db: <%= GlobalSetting.redis_db %>

development:
  <<: *defaults

profile:
  <<: *defaults

test:
  <<: *defaults
  db: 1

staging:
  <<: *defaults

production:
  <<: *defaults
  host: "albacore.redistogo.com"
  port: 10653
  password: "f34917b08e9771091bdd47a37ff08eca"
